name: trident_feat_only_shared_coords
pipeline: trident_feat_only_shared_coords
defaults:
  coords_dir: 20x_256px_0px_overlap
  job_dir: /storage/brno2/home/filipsec/MIL/data/trident_out/panda_ensemble_grandqc_20x_256_ov0
  wsi_dir: /storage/brno2/home/filipsec/MIL/data/raw/train_images
  repo_dir: /storage/brno2/home/filipsec/repos/trident
  repo_root: /storage/brno2/home/filipsec/MIL
  conda_env: /storage/brno2/home/filipsec/.conda/envs/trident
  python_bin: /storage/brno2/home/filipsec/.conda/envs/trident/bin/python
  wsi_ext: .tiff
  mag: 20
  overlap: 0
  gpu: 0
  max_workers: 4
  cache_batch_size: 8
  patch_size: null
  feat_batch_size: null
