"""Default configuration parameters."""

DEFAULT_DOWNSAMPLE = 32
DEFAULT_TILE_PX = 512
DEFAULT_STRICT_THRESHOLD = True
DEFAULT_OPEN_CLOSE = 5
DEFAULT_MIN_FRAC = 1e-3
DEFAULT_QC_TILES = 64
DEFAULT_QC_SIZE = 128
